sbs/urls.py
from django.conf.urls import url

from sbs.Views import DashboardViews, AthleteViews, RefereeViews, ClubViews, CoachViews, DirectoryViews, UserViews, \
    CompetitionViews, AdminViews, HelpViews, PageViews, PreRegistration, ActivityView, ReferenceView, QuestionViews, \
    LogViews, ProductView, Aktarma, ClaimView, PenalView,ArsivView

app_name = 'sbs'

urlpatterns = [

    # Dashboard
    url(r'anasayfa/admin/$', DashboardViews.return_admin_dashboard, name='admin'),
    url(r'anasayfa/sehir-sporcu-sayisi/$', DashboardViews.City_athlete_cout, name='sehir-sporcu-sayisi'),
    url(r'anasayfa/sporcu/$', DashboardViews.return_athlete_dashboard, name='sporcu'),
    url(r'anasayfa/hakem/$', DashboardViews.return_referee_dashboard, name='hakem'),
    url(r'anasayfa/antrenor/$', DashboardViews.return_coach_dashboard, name='antrenor'),
    url(r'anasayfa/federasyon/$', DashboardViews.return_directory_dashboard, name='federasyon'),
    url(r'anasayfa/kulup-uyesi/$', DashboardViews.return_club_user_dashboard, name='kulup-uyesi'),

    # Sporcular
    url(r'sporcu/sporcu-ekle/$', AthleteViews.return_add_athlete, name='sporcu-ekle'),
    url(r'sporcu/sporcu-birlestir/(?P<pk>\d+)$', AthleteViews.sporcu_sec, name='sporcu-birlestir'),
    url(r'sporcu/sporcu-birlestironay/$', AthleteViews.sporcu_birlestir, name='sporcu-birlestir-onay'),
    url(r'sporcu/sporcu-ekle-antrenor/$', AthleteViews.return_add_athlete_antrenor, name='sporcu-ekle-antrenor'),
    url(r'sporcu/sporcular/$', AthleteViews.return_athletes, name='sporcular'),
    url(r'sporcu/sporcular/antrenor/$', AthleteViews.return_athletes_antrenor, name='sporcular-antrenor'),

    # pagenation deneme
    url(r'page/$', PageViews.deneme, name='deneme'),
    url(r'sporcularajax/$', PageViews.return_athletesdeneme, name='sporculardeneme'),

    url(r'sporcu/sporcuKusakEkle/(?P<pk>\d+)$', AthleteViews.sporcu_kusak_ekle, name='sporcu-kusak-ekle'),
    url(r'sporcu/sporcuKusakDuzenle/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_kusak_duzenle,
        name='sporcu-kusak-duzenle'),
    url(r'sporcu/sporcuLisansEkle/(?P<pk>\d+)$', AthleteViews.sporcu_lisans_ekle, name='sporcu-lisans-ekle'),

    url(r'sporcu/sporcuBelgeEkle/(?P<pk>\d+)$', AthleteViews.sporcu_belge_ekle, name='sporcu-belge-ekle'),
    url(r'sporcu/sporcuCezaEkle/(?P<pk>\d+)$', AthleteViews.sporcu_ceza_ekle, name='sporcu-ceza-ekle'),

    url(r'sporcu/sporcuLisansEkle/antrenor/(?P<pk>\d+)$', AthleteViews.sporcu_lisans_ekle_antrenor,
        name='sporcu-lisans-ekle-antrenor'),
    url(r'sporcu/sporcuLisansDuzenle/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_lisans_duzenle,
        name='sporcu-lisans-duzenle'),
    url(r'sporcu/sporcuLisansDuzenle/antrenor/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_lisans_duzenle_antrenor,
        name='sporcu-lisans-duzenle-antrenor'),
    url(r'sporcu/sporcuLisansDuzenleMobil/(?P<count>\d+)$', AthleteViews.sporcu_lisans_duzenle_mobil,
        name='sporcu-lisans-duzenle-mobil'),
    # ilk degeri verebilmek icin yönlendirme amaci ile kullanildi.
    url(r'sporcu/sporcuLisansDuzenleMobil/$', AthleteViews.sporcu_lisans_duzenle_mobil_ilet,
        name='sporcu-lisans-duzenle-mobil-ilet'),

    url(r'sporcu/sporcuLisansDuzenle/onayla/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_lisans_onayla, name='sporcu-lisans-onayla'),

    url(r'sporcu/sporcuLisansDuzenle/reddet/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_lisans_reddet, name='sporcu-lisans-reddet'),
    url(r'sporcu/sporcuLisansDuzenle/lisanssil/(?P<pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_lisans_sil,
        name='sporcu-lisans-sil'),
    url(r'sporcu/sporcuLisansListesi/onayla/(?P<license_pk>\d+)$',
        AthleteViews.sporcu_lisans_listesi_onayla, name='sporcu-lisans-listesi-onayla'),
    url(r'sporcu/sporcuLisansListesi/onaylaMobil/(?P<license_pk>\d+)/(?P<count>\d+)$',
        AthleteViews.sporcu_lisans_listesi_onayla_mobil, name='sporcu-lisans-listesi-onayla-mobil'),
    # lisans listesinin hepsini onaylama
    url(r'sporcu/sporcuLisansListesi/hepsinionayla/$', AthleteViews.sporcu_lisans_listesi_hepsionay,
        name='sporcu-lisans-hepsini-onayla'),
    # lisanslarin hepsini reddetme
    url(r'sporcu/sporcuLisansListesi/hepsiniReddet/$', AthleteViews.sporcu_lisans_listesi_hepsireddet,
        name='sporcu-lisans-hepsini-reddet'),

    # hepsini beklemeye al
    url(r'sporcu/sporcuLisansListesi/hepsinibekle/$', AthleteViews.sporcu_bekle,
        name='sporcu-lisans-hepsini-bekle'),

    url(r'sporcu/sporcuLisansListesi/reddet/(?P<license_pk>\d+)$',
        AthleteViews.sporcu_lisans_listesi_reddet, name='sporcu-lisans-listesi-reddet'),
    url(r'sporcu/sporcuLisansListesiMobil/reddet/(?P<license_pk>\d+)/(?P<count>\d+)$',
        AthleteViews.sporcu_lisans_listesi_reddet_mobil, name='sporcu-lisans-listesi-reddet-mobil'),
    url(r'sporcu/kusak/$', AthleteViews.return_belt, name='kusak'),
    url(r'sporcu/kusak/sil/(?P<pk>\d+)$', AthleteViews.categoryItemDelete,
        name='categoryItem-delete'),
    url(r'sporcu/kusakDuzenle/(?P<pk>\d+)$', AthleteViews.categoryItemUpdate,
        name='categoryItem-duzenle'),
    url(r'sporcu/sporcuKusakDuzenle/onayla/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_kusak_onayla, name='sporcu-kusak-onayla'),
    url(r'sporcu/sporcuKusakReddet/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_kusak_reddet, name='sporcu-kusak-reddet'),
    url(r'sporcu/sporcuKusakDuzenle/kusaksil/(?P<pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_kusak_sil,
        name='sporcu-kusak-sil'),

    # kuşaklarin hepsini beklemeye al
    url(r'sporcu/sporcuKusakbekle',
        AthleteViews.sporcu_kusak_bekle, name='sporcu-kusak-bekle'),
    # kuşak listesinin hepsini onayla
    url(r'sporcu/sporcuKusakListesi/hepsinionayla/$',
        AthleteViews.sporcu_kusak_listesi_hepsinionayla, name='sporcu-kusak-listesi-hepsinionayla'),

    # kuşak hepsini reddet
    url(r'sporcu/sporcuKusakDuzenle/reddet/$',
        AthleteViews.sporcu_kusak_hepsinireddet, name='sporcu-kusak-hepsinireddet'),

    # kusak listesi onay
    url(r'sporcu/sporcuKusakListesi/onayla/(?P<belt_pk>\d+)$',
        AthleteViews.sporcu_kusak_listesi_onayla, name='sporcu-kusak-listesi-onayla'),
    # kuşak listesi reddet
    url(r'sporcu/sporcuKusakListesi/reddet/(?P<belt_pk>\d+)$',
        AthleteViews.sporcu_kusak_listesi_reddet, name='sporcu-kusak-listesi-reddet'),

    url(r'sporcu/sporcuDuzenle/(?P<pk>\d+)$', AthleteViews.updateathletes, name='update-athletes'),
    url(r'sporcu/sporcu-kusak-listesi/$', AthleteViews.sporcu_kusak_listesi, name='kusak-listesi'),
    url(r'sporcu/sporcu-lisans-listesi/$', AthleteViews.sporcu_lisans_listesi, name='lisans-listesi'),
    url(r'sporcu/sporcu-profil-guncelle/$', AthleteViews.updateAthleteProfile,
        name='sporcu-profil-guncelle'),

    url(r'sporcu/sporcuBelgeKaldir/(?P<athlete_pk>\d+)/(?P<document_pk>\d+)$', AthleteViews.athlete_document_delete,
        name='sporcu-belge-kaldir'),
    url(r'sporcu/sporcuCezaKaldir/(?P<athlete_pk>\d+)/(?P<document_pk>\d+)$', AthleteViews.athlete_penal_delete,
        name='sporcu-ceza-kaldir'),

    # Hakemler
    url(r'hakem/hakem-ekle/$', RefereeViews.return_add_referee, name='hakem-ekle'),
    url(r'hakem/hakemler/$', RefereeViews.return_referees, name='hakemler'),
    url(r'hakem/seviye/$', RefereeViews.return_level, name='seviye'),
    url(r'hakem/seviye/sil/(?P<pk>\d+)$', RefereeViews.categoryItemDelete,
        name='categoryItem-delete-seviye'),
    url(r'hakem/seviye/(?P<pk>\d+)$', RefereeViews.categoryItemUpdate,
        name='categoryItem-duzenle-seviye'),
    url(r'hakem/hakemler/sil/(?P<pk>\d+)$', RefereeViews.deleteReferee,
        name='referee-delete'),
    url(r'hakem/hakemler/reddet/basvuru/(?P<pk>\d+)$', RefereeViews.refencedeleteReferee,
        name='referee-reddet-basvuru'),
    url(r'hakem/hakemler/onayla/basvuru/(?P<pk>\d+)$', RefereeViews.refenceapprovalReferee,
        name='referee-onayla-basvuru'),
    url(r'hakem/hakemDuzenle/(?P<pk>\d+)$', RefereeViews.updateReferee,
        name='hakem-duzenle'),
    url(r'hakem/hakemDuzenle-basvuru/(?P<pk>\d+)$', RefereeViews.referenceUpdateReferee,
        name='hakem-duzenle-basvuru'),
    url(r'hakem/hakem-profil-guncelle/$', RefereeViews.updateRefereeProfile,
        name='hakem-profil-guncelle'),
    # /kademe
    url(r'hakem/Hakem-kademe-ekle/(?P<pk>\d+)$', RefereeViews.hakem_kademe_ekle, name='hakem-kademe-ekle'),
    url(r'hakem/Kademe-Duzenle/onayla/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_onay,
        name='kademe-onayla-hakem'),
    url(r'hakem/Kademe-Duzenle/reddet/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_reddet,
        name='kademe-reddet-hakem'),
    url(r'hakem/Kademe-Duzenle/guncelle/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_update,
        name='kademe-guncelle-hakem'),
    url(r'hakem/Kademe-Duzenle/sil/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_delete,
        name='Kademe-sil-hakem'),
    # /vize
    url(r'hakem/hakem-vize-ekle/(?P<pk>\d+)$', RefereeViews.visa_ekle, name='hakem-vize-ekle'),
    url(r'hakem/Vize-Duzenle/onayla/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.visa_onay,
        name='hakem-vize-onayla'),
    url(r'hakem/Vize-Duzenle/reddet/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.visa_reddet,
        name='hakem-vize-reddet'),
    url(r'hakem/Vize-Duzenle/guncelle/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.vize_update,
        name='hakem-vize-guncelle'),
    url(r'hakem/Vize-Duzenle/sil/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.vize_delete,
        name='hakem-vize-sil'),
    url(r'hakem/hakemBelgeEkle/(?P<pk>\d+)$', RefereeViews.hakem_belge_ekle, name='hakem-belge-ekle'),

sbs/models/Abirim.py
from django.db import models

class Abirim(models.Model):

    name = models.CharField(max_length=120, null=True, blank=True, verbose_name='İsim')
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % (self.name)

sbs/models/AbirimParametre.py
from django.db import models

from sbs.models.Abirim import Abirim
from sbs.models.Aevrak import Aevrak
from sbs.services import general_methods


class AbirimParametre(models.Model):
    aDate = 'date'
    aString = 'string'
    aNumber = 'number'
    aYear='year'

    Type = (
        (aDate, 'Tarih'),
        (aString, 'Metin'),
        (aNumber, 'Sayi'),
        ( aYear,'Yil')

    )

    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=120,  null=True, blank=True, verbose_name='Başlık')
    type = models.CharField(max_length=128, verbose_name='Türü ', choices=Type,default=aString)
    birim = models.ForeignKey(Abirim, on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='Birim')

    def __str__(self):
        return '%s' % (self.title)

sbs/models/ActiveGroup.py
from random import choices

from django.contrib.auth.models import User, Group
from django.db import models


class ActiveGroup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='aktivUser')
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, verbose_name='aktivGroup')

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

sbs/models/Activity.py
import enum

from django.db import models
from sbs.models.EnumFields import EnumFields
class Activity(models.Model):

    DOMESTİC = 0
    OVERSEAS = 1
    EDUCATİON = 2
    CAMP = 3

    TYPE = (
        (DOMESTİC, 'YURT İÇİ FAALİYETLERİ'),
        (OVERSEAS, 'YURT DIŞI FAALİYETLERİ'),
        (EDUCATİON, 'EGİTİM FAALİYETLERİ'),
        (CAMP, 'KAMP FAALİYETLERİ'),
    )
    type = models.IntegerField(db_column='Type', blank=False, null=False, choices=TYPE)  # Field name made lowercase.
    creationDate = models.DateTimeField(db_column='creationDate', blank=True, null=True,
                                        auto_now_add=True)  # Field name made lowercase.
    operationDate = models.DateTimeField(db_column='operationDate', blank=True, null=True,
                                         auto_now_add=True)  # Field name made lowercase.
    startDate = models.DateTimeField(db_column='startDate', blank=True, null=True)  # Field name made lowercase.
    finishDate = models.DateTimeField(db_column='finishDate', blank=True, null=True)  # Field name made lowercase.
    name = models.CharField(max_length=255, blank=False, null=False)
    eventPlace = models.CharField(db_column='eventPlace', max_length=45, blank=True,
                                  null=True)  # Field name made lowercase.
    year = models.IntegerField(blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return '%s ' % self.name

    # def save(self, force_insert=False, force_update=False):
    #     if self.name:
    #         self.name = self.name.upper()
    #
    #     super(Activity, self).save(force_insert, force_update)

sbs/models/Adosya.py
from django.db import models
from sbs.models.Aevrak import Aevrak
from sbs.models.Aklasor import Aklasor
class Adosya(models.Model):
    sirano = models.IntegerField(null=True, blank=True)
    klasor = models.ForeignKey(Aklasor, on_delete=models.SET_NULL,null=True, blank=True)
    evrak=models.ManyToManyField(Aevrak)
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)

sbs/models/AdosyaParametre.py
from django.db import models

from sbs.models.AbirimParametre import AbirimParametre
from sbs.models.Adosya import Adosya


class AdosyaParametre(models.Model):

    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    value = models.CharField(max_length=120, null=True, blank=True, verbose_name='value')
    dosya = models.ForeignKey(Adosya, on_delete=models.DO_NOTHING,null=False, blank=False)
    parametre=models.ForeignKey(AbirimParametre,on_delete=models.DO_NOTHING,null=True, blank=True)

    def __str__(self):
        return '%s' % (self.value)

sbs/models/Aevrak.py
from django.db import models
class Aevrak(models.Model):
    file = models.FileField(null=False, blank=False)
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s ' % self.file

sbs/models/Aklasor.py
from django.db import models

from sbs.models.CategoryItem import CategoryItem
from sbs.models.Abirim import Abirim

class Aklasor(models.Model):
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=120, null=False, blank=False, verbose_name='Tanımı')
    sirano = models.IntegerField(null=False, blank=False,verbose_name='Sıra Numarası')
    location = models.ForeignKey(CategoryItem, on_delete=models.SET_NULL,null=True, blank=True,verbose_name='Konumu')
    birim = models.ForeignKey(Abirim, on_delete=models.SET_NULL,null=True, blank=True,verbose_name='Birim')

    def __str__(self):
        return '%s ' % self.name

sbs/models/Athlete.py
from random import choices

from django.contrib.auth.models import User
from django.db import models

from sbs.models.License import License
from sbs.models.Level import Level
from sbs.models.Person import Person
from sbs.models.Communication import Communication


class Athlete(models.Model):

    person = models.OneToOneField(Person, on_delete=models.CASCADE, db_column='person')
    communication = models.OneToOneField(Communication, on_delete=models.CASCADE, db_column='communication')
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_column='user')
    licenses = models.ManyToManyField(License)
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    oldpk = models.IntegerField(null=True, blank=True)
    iban = models.CharField(max_length=120, null=True, blank=True, verbose_name='İban Adresi')

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    # class Meta:
    #     ordering = ['pk']
    #     default_permissions = ()
    #     db_table = 'athlete'
    #     # managed = False

sbs/models/Branch.py
from django.db import models


class Branch(models.Model):
    name = models.CharField(blank=True, null=True, max_length=120, verbose_name='Branş Adı')
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s ' % self.name

    # class Meta:
    #     default_permissions = ()

sbs/models/Category.py
from django.db import models


class Category(models.Model):
    kategoriid = models.IntegerField(primary_key=True)
    kategoriadi = models.CharField(max_length=20, blank=True, null=True)
    erkek = models.IntegerField(blank=True, null=True)
    bayan = models.IntegerField(blank=True, null=True)
    sayi = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return '%s ' % self.kategoriadi

sbs/models/City.py
from django.db import models


class City(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Şehir')

    def __str__(self):
        return '%s' % self.name

    # def save(self, force_insert=False, force_update=False):
    #     self.name = self.name.upper()
    #     super(City, self).save(force_insert, force_update)

    # class Meta:
    #     default_permissions = ()
    #     db_table = 'city'
    #     managed = False

sbs/templates/sporcu/Sporcu-ceza-ekle.html
{% extends 'base_layout.html' %}
{% block content %}

    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}


    <section class="content-header">
        <h1>
            Sporcu Ceza Ekle

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Sporcu Ceza Ekle</a></li>

        </ol>
    </section>
    <section class="content">

        <form method="post" enctype="multipart/form-data" role="form">
            {% csrf_token %}
            <div class="row">

                <div class="col-lg-3">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Bilgiler</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label> {{ ceza.penal.label }}</label>
                                        {{ ceza.penal }}
                                    </div>
                                    <div class="form-group">
                                        <label> {{ ceza.file.label }}</label>
                                        {{ ceza.file }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <button class="btn btn-primary" type="submit">Kaydet</button>
                        </div>


                    </div>

                </div>
            </div>

        </form>


    </section>

{% endblock %}

sbs/templates/sporcu/sporcu-lisans-mobil-onay.html
{% extends 'base_layout.html' %}


{% block content %}

    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}

    <div class="row">


        <div class="col-lg-1 col-sm-2 col-xs-2" style="height: 600px;"
             onclick="location.href='{% url "sbs:sporcu-lisans-duzenle-mobil" count=geri %}'">
            <br><br><br><br><br><br><br>


            <a href="{% url "sbs:sporcu-lisans-duzenle-mobil" count=geri %}" type="button"
               class="btn btn-default btn-lg center-block">Geri</a>
        </div>

        <div class="col-lg-10 col-sm-8 col-xs-8">

            <div class="row">

                <div class="col-lg-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Bilgiler</h3>
                        </div>
                        <div class="box-body">

                            <div class="col-lg-12 text-center">
                                <td>
                                    <img src="/media/{{ license.lisansPhoto }}" class="user-image" alt="None"
                                         style=" width:80%;height: 80%;">
                                </td>
                            </div>


                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label> İsim </label>
                                    {{ license.athlete_set.first }}
                                </div>

                                <div class="form-group">

                                    <label> Baslangıc Tarihi </label>
                                    {{ license.startDate }}
                                </div>
                                <div class="form-group">
                                    <label>Bitiş Tarihi</label>
                                    {{ license.expireDate }}
                                </div>


                                <div class="form-group">
                                    <label>Branş</label>
                                    {{ license.branch }}
                                </div>
                                <div class="form-group">
                                    <label>Lisans Photo</label>
                                    <a href="/media/{{ license.lisansPhoto }}" target="_blank">{{ license.lisansPhoto }}
                                    </a>
                                </div>

                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label> Lisans Numarasi </label>
                                    <h4> {{ license.licenseNo }}</h4>
                                </div>


                                <div class="form-group">
                                    <label>Verildigi il </label>
                                    {{ license.cityHeadShip }}
                                </div>

                                <div class="form-group">
                                    <label>Kulubü:</label>
                                    {{ license.sportsClub }}
                                </div>
                                <div class="form-group">
                                    <label>Onay Durumu :</label>
                                    {{ license.status }}-{{ license.reddetwhy }}
                                </div>


                            </div>
                            <div class="col-lg-12">
                                {% if aktif == 'Admin' %}

                                    <div class="col-lg-10">
                                        <form action="{% url "sbs:sporcu-lisans-listesi-reddet-mobil" license_pk=license.pk  count=say %}"
                                              method="post">
                                            {% csrf_token %}
                                            <div class="input-group margin ">
                                                <input type="text" name="text" class="form-control"><br>
                                                <span class="input-group-btn">
                                                  <button type="submit" class="btn btn-danger">reddet!</button>
                                                      </span>
                                            </div>
                                        </form>


                                    </div>
                                    <div class="col-lg-2">

                                        <div class="input-group margin text-left"><br>
                                            <span class="input-group-btn">
                                        <a href="{% url "sbs:sporcu-lisans-listesi-onayla-mobil" license_pk=license.pk  count=say %}"
                                           type="button" class="btn btn-success pull-left  "><i
                                                class="fa fa-edit"></i>Onayla
                                        </a>
                                            </span>
                                        </div>

                                    </div>
                                {% endif %}

                            </div>


                        </div>


                    </div>

                </div>
            </div>

        </div>


        <div class="col-lg-1 col-sm-2 col-xs-2" style=" height: 600px;"
             onclick="location.href='{% url "sbs:sporcu-lisans-duzenle-mobil" count=ileri %}'">
            <br><br><br><br><br><br><br>
            <a href="{% url "sbs:sporcu-lisans-duzenle-mobil" count=ileri %}" type="button"
               class="btn btn-default btn-lg pull-left center-block"> ileri
            </a>
        </div>


    </div>



{% endblock %}